# Naive Bayes Algorithm

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import  matplotlib.pyplot as plt



In [2]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.model_selection import  train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.datasets import load_iris

In [3]:
#select the features and the target variables
iris=load_iris()
X=iris.data
y=iris.target

#train test split the data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [4]:
#initialize the model
model=GaussianNB()

#train the model
model.fit(X_train,y_train)

#predict the model
y_pred=model.predict(X_test)

#evaluate the model
print('accuracy score: ', accuracy_score(y_test,y_pred))
print('classification report: \n', classification_report(y_test,y_pred))
print('confusion_matrix: \n', confusion_matrix(y_test,y_pred))


accuracy score:  0.9777777777777777
classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45

confusion_matrix: 
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


### Multinomial naive bayes

In [5]:
#initialize the model
model=MultinomialNB()

#train the model
model.fit(X_train,y_train)

#predict the model
y_pred=model.predict(X_test)

#evaluate the model
print('accuracy_score: ', accuracy_score(y_test,y_pred))
print('confusion_matrix: \n', confusion_matrix(y_test,y_pred))
print('classification_report: \n', classification_report(y_test, y_pred))


accuracy_score:  0.9555555555555556
confusion_matrix: 
 [[19  0  0]
 [ 0 12  1]
 [ 0  1 12]]
classification_report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      0.92      0.92        13
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45



#bernoulli naive bayes

In [6]:
#call the model
model=BernoulliNB()

#train the model
model.fit(X_train,y_train)

#predict the model
y_pred=model.predict(X_test)

#evaluate the model
print('accuracy_score', accuracy_score(y_test,y_pred))
print('confusion_matrix: \n',confusion_matrix(y_test,y_pred))
print('classification_report: \n', classification_report(y_test,y_pred))

accuracy_score 0.28888888888888886
confusion_matrix: 
 [[ 0 19  0]
 [ 0 13  0]
 [ 0 13  0]]
classification_report: 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.29      1.00      0.45        13
           2       0.00      0.00      0.00        13

    accuracy                           0.29        45
   macro avg       0.10      0.33      0.15        45
weighted avg       0.08      0.29      0.13        45



c:\Users\ishas\miniconda3\envs\mlenv\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\ishas\miniconda3\envs\mlenv\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\ishas\miniconda3\envs\mlenv\Lib\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
